const fs=require('fs'),vm=require('vm'),{createCanvas,Image}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const source=fs.readFileSync('dist/render.html','utf8'),els={},events={},wEvents={};
function element(){return {style:{},children:[],classList:{toggle(){}},append(...children){this.children.push(...children)},appendChild(child){this.children.push(child);if(child.id)els[child.id]=child;},replaceChildren(){this.children=[];},setAttribute(){},addEventListener(){},getContext:()=>createCanvas(960,580).getContext('2d')};}
for(const m of source.matchAll(/id="([^"]+)"[^>]*>/g)){const v=m[0].match(/value="([^"]*)"/);els[m[1]]={...element(),value:v?v[1]:'',style:{},innerHTML:'',textContent:'',open:false,checked:/checked/.test(m[0]),hidden:false,appendChild:element().appendChild,addEventListener(){},dispatchEvent(e){if(this['on'+e.type])this['on'+e.type](e)},setAttribute(){}};}
for(const p of ['cs','ci']){els[p+'-view'].value='3d';els[p+'-mode'].value='now';els[p+'-canopy'].value='full';els[p+'-data'].textContent=source.match(new RegExp('<script id="'+p+'-data"[^>]*>([\\s\\S]*?)<\\/script>'))[1];const c=createCanvas(736,490);c.clientWidth=736;c.clientHeight=490;els[p+'-map']=c;}
els['ci-floor'].value='0';els['ci-doors'].value='open';els['walk-start'].value='yard';
for(const id of ['cleveland-sun-explorer','cleveland-indoor-sun'])els[id].querySelector=s=>els[s.slice(1)];
const cols={'--foreground':'#163444','--muted-foreground':'#526776','--muted':'#e4ebef','--secondary':'#eef2f5','--border':'#bdccd5','--orange':'#e79a25','--green':'#3f8059','--blue':'#2d8dbc','--background':'#f7fafc'};
const gl=new Proxy({getShaderParameter:()=>true,getProgramParameter:()=>true,createShader:()=>({}),createProgram:()=>({}),createBuffer:()=>({}),getAttribLocation:()=>0,getUniformLocation:()=>({})},{get:(o,k)=>k in o?o[k]:/^[A-Z_]+$/.test(k)?1:()=>{}});
els['walk-canvas'].clientWidth=960;els['walk-canvas'].clientHeight=570;els['walk-canvas'].getContext=()=>gl;els['walk-mini']=createCanvas(140,160);els['fl-canvas'].clientWidth=960;els['fl-canvas'].clientHeight=580;els['fl-canvas'].getContext=()=>gl;els['fl-canvas'].parentElement=element();
let animation;const win={devicePixelRatio:1,matchMedia:()=>({addEventListener(){}}),addEventListener:(n,f)=>wEvents[n]=f};
const scope={document:{getElementById:s=>els[s],createElement:element,documentElement:{},querySelectorAll:()=>[],addEventListener:(n,f)=>(events[n]??=[]).push(f),dispatchEvent:e=>events[e.type]?.forEach(f=>f(e))},window:win,Image,ResizeObserver:class{constructor(cb){this.cb=cb}observe(){this.cb()}},MutationObserver:class{observe(){}},getComputedStyle:e=>({getPropertyValue:n=>cols[n],color:cols[e.style?.color?.slice(4,-1)]}),setTimeout,clearTimeout,setInterval,clearInterval,console,Math,Date,Float32Array,Uint16Array,CustomEvent:class{constructor(t){this.type=t}},Event:class{constructor(t){this.type=t}},devicePixelRatio:1,requestAnimationFrame:f=>{animation=f;return 1},cancelAnimationFrame(){}};
vm.createContext(scope);for(const js of source.matchAll(/<script>([\s\S]*?)<\/script>/g))vm.runInContext(js[1],scope);vm.runInContext(fs.readFileSync('dist/walk.js','utf8'),scope);
win.ClevelandWalk.activate();animation(16);let d=win.ClevelandWalk.diagnostics();console.log('Backyard',d);if(!d.finite||d.vertices<1000)throw Error('Invalid scene');
els['walk-start'].value='room-0-4';els['walk-start'].onchange();animation(32);d=win.ClevelandWalk.diagnostics();console.log('Study',d);if(!d.finite||d.player.z<2)throw Error('Invalid indoor eye height');
els['walk-start'].value='room-1-1';els['walk-start'].onchange();animation(48);d=win.ClevelandWalk.diagnostics();console.log('Sunroom',d);if(d.player.z<5||!d.finite)throw Error('Invalid second floor');
win.ClevelandWalk.pause();console.log('All scenes generated finite geometry; level switching passed');

const assert=(x,m)=>{if(!x)throw Error(m)};const inn=els['cleveland-indoor-sun'].sunModel;
vm.runInContext(fs.readFileSync('dist/floors.js','utf8'),scope);
for(const level of ['0','1']){els['ci-floor'].value=level;els['ci-floor'].onchange();win.ClevelandFloors.activate();animation(200);const d=win.ClevelandFloors.diagnostics();assert(d.finite&&d.vertices>1000,'Invalid orbit floor');for(const key of ['right','up','forward'])assert(Math.abs(Math.hypot(...d.basis[key])-1)<1e-8,'Camera basis length');assert(Math.abs(d.basis.up.reduce((s,v,i)=>s+v*d.basis.forward[i],0))<1e-8,'Camera orthogonality');console.log('Orbit',d.floor,d.vertices);win.ClevelandFloors.pause();}
const jumps=win.ClevelandWalk.jumpLocations();assert(jumps.length>=20,'Missing jump locations');for(const [id,p] of jumps){els['walk-start'].value=id;els['walk-start'].onchange();const d=win.ClevelandWalk.diagnostics();assert([d.player.x,d.player.y,d.player.z].every(Number.isFinite),'Invalid jump '+id);assert(Math.abs(d.player.x-p.x)<1e-9,'Jump did not move');}console.log('Jump destinations checked:',jumps.length);
let directFound=0;
for(const level of ['0','1']){els['ci-floor'].value=level;els['ci-floor'].onchange();const I=inn.state();const tree=(mode)=>els['ci-canopy'].value=mode;tree('none');els['ci-doors'].value='open';
 for(const date of ['2026-03-21','2026-06-21','2026-09-21','2026-12-21'])for(const time of [480,660,840,1020]){const sun=inn.sun(time,date);tree('none');els['ci-doors'].value='open';const open=I.samples.map(p=>I.indoorShade(p,sun));directFound+=open.filter(c=>c===0).length;tree('full');const trees=I.samples.map(p=>I.indoorShade(p,sun));assert(trees.every((c,i)=>c!==0||open[i]===0),'Trees introduced direct sun');tree('none');els['ci-doors'].value='closed';const closed=I.samples.map(p=>I.indoorShade(p,sun));assert(closed.every((c,i)=>c!==0||open[i]===0),'Closed doors introduced sun');}
 assert(I.samples.every(p=>I.indoorShade(p,{x:0,y:0,z:-1})===3),'Night leak');assert(I.samples.every(p=>I.indoorShade(p,{x:0,y:0,z:1})!==0),'Ceiling leak');
 const saved=I.floor.walls.map(w=>w.holes);I.floor.walls.forEach(w=>w.holes=[]);for(const time of [480,840,1020])assert(I.samples.every(p=>I.indoorShade(p,inn.sun(time,'2026-06-21'))!==0),'Sealed exterior leaked sunlight');I.floor.walls.forEach((w,i)=>w.holes=saved[i]);
}
assert(directFound>0,'Sun never reaches any room');console.log('Sun checks passed: seasonal samples, tree/door monotonicity, night, ceilings, sealed walls. Direct hits:',directFound);

els['ci-doors'].value='open';els['ci-canopy'].value='full';win.ClevelandWalk.activate();animation(250);assert(els['walk-sun-bearing'].textContent.length>0,'Missing sun HUD');win.ClevelandWalk.pause();console.log('First-person sun indicator passed');
