import assert from 'node:assert/strict';
import {generateKeyPair,exportJWK,createLocalJWKSet,SignJWT} from 'jose';
import {createAccessVerifier,normalizeEmails,validateSettings} from '../remote/sharing-auth.mjs';
import {SharingManager} from '../remote/sharing.mjs';

const {privateKey,publicKey}=await generateKeyPair('RS256');
const jwk=await exportJWK(publicKey);jwk.kid='test-key';
const config={enabled:true,hostname:'daylight.example.com',authDomain:'daylight-test.cloudflareaccess.com',audience:'test-audience',emails:['owner@example.com']};
const verify=createAccessVerifier(()=>config,{resolveKeys:createLocalJWKSet({keys:[jwk]})});
const sign=(email='owner@example.com',overrides={})=>new SignJWT({email,...overrides}).setProtectedHeader({alg:'RS256',kid:'test-key'}).setIssuer('https://'+config.authDomain).setAudience(config.audience).setSubject('test-user').setIssuedAt().setExpirationTime('1h').sign(privateKey);
const request=token=>({headers:{host:config.hostname,'cf-access-jwt-assertion':token}});
const token=await sign();assert.equal((await verify(request(token))).email,'owner@example.com');
await assert.rejects(verify(request(await sign('stranger@example.com'))));
await assert.rejects(verify({headers:{host:config.hostname,'cf-access-authenticated-user-email':'owner@example.com',cookie:'daylight=known-pair-key'}}));
await assert.rejects(verify(request(token.slice(0,-5)+'wrong')));
await assert.rejects(verify({...request(token),headers:{...request(token).headers,host:'wrong.example.com'}}));
config.emails=[];await assert.rejects(verify(request(token)));config.emails=['owner@example.com'];config.enabled=false;await assert.rejects(verify(request(token)));config.enabled=true;
const expired=await new SignJWT({email:'owner@example.com'}).setProtectedHeader({alg:'RS256',kid:'test-key'}).setIssuer('https://'+config.authDomain).setAudience(config.audience).setSubject('user').setIssuedAt(1).setExpirationTime(2).sign(privateKey);await assert.rejects(verify(request(expired)));
assert.deepEqual(normalizeEmails('OWNER@example.com, owner@example.com\nfriend@example.com'),['owner@example.com','friend@example.com']);
for(const bad of ['','*@example.com','@example.com','person@example.com\nmalformed'])assert.throws(()=>normalizeEmails(bad));
assert.throws(()=>validateSettings({accountId:'a'.repeat(32),zoneId:'b'.repeat(32),hostname:'https://example.com',emails:['owner@example.com']}));

const calls=[],manager=new SharingManager('test-root');
manager.save=async()=>{};manager.readSecrets=async()=>({apiToken:'test-only'});manager.storeSecrets=async()=>{};manager.stopProcess=async()=>{};manager.startProcess=async()=>calls.push(['START']);
manager.api=async(token,route,method='GET',body)=>{calls.push([method,route,body]);
 if(route==='/zones/'+ 'b'.repeat(32))return {name:'example.com',status:'active',account:{id:'a'.repeat(32)}};
 if(route.endsWith('/access/organizations'))return {auth_domain:config.authDomain};
 if(route.includes('/dns_records?'))return [];
 if(route.endsWith('/identity_providers'))return [{id:'otp-id',type:'onetimepin'}];
 if(route.endsWith('/access/policies'))return {id:'policy-id'};
 if(route.endsWith('/access/apps'))return {id:'app-id',aud:'test-audience'};
 if(route.endsWith('/cfd_tunnel'))return {id:'tunnel-id'};
 if(route.endsWith('/configurations'))return {};
 if(route.endsWith('/dns_records'))return {id:'dns-id'};
 if(route.endsWith('/token'))return 'test-tunnel-token';
 throw Error('Unexpected API route '+route);
};
await manager.configure({accountId:'a'.repeat(32),zoneId:'b'.repeat(32),hostname:config.hostname,emails:['owner@example.com']});
const app=calls.findIndex(c=>c[1]?.endsWith('/access/apps')),dns=calls.findIndex(c=>c[1]?.endsWith('/dns_records'));assert(app>=0&&dns>app);assert.equal(calls.at(-1)[0],'START');
const ingress=calls.find(c=>c[1]?.endsWith('/configurations'))[2].config.ingress;assert.equal(ingress[0].originRequest.access.required,true);assert.equal(ingress[0].service,'http://127.0.0.1:5184');assert.equal(ingress[1].service,'http_status:404');
assert.deepEqual(calls.find(c=>c[1]?.endsWith('/access/policies'))[2].include,[{email:{email:'owner@example.com'}}]);
let removedBeforeAPI=false;manager.config.emails=['owner@example.com','removed@example.com'];
manager.api=async(_t,_r,m='GET')=>{removedBeforeAPI=!manager.config.emails.includes('removed@example.com');if(m==='PUT')throw Error('Simulated network failure');return {name:'test',require:[]};};
await assert.rejects(manager.updateEmails(['owner@example.com','new@example.com']));assert(removedBeforeAPI);assert.deepEqual(manager.config.emails,['owner@example.com']);
await manager.disable();assert.equal(manager.config.enabled,false);
console.log(JSON.stringify({signedIdentityRequired:true,forgedHeadersAndPairKeysRejected:true,expiredAndUnlistedUsersRejected:true,accessPolicyBeforeDNS:true,tunnelRequiresAccessJWT:true,removalFailsClosed:true,disableWorks:true,liveCloudflareProvisioningTested:false},null,2));
