import './style.css';
import * as T from 'three';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {WebGLPathTracer,GradientEquirectTexture,DenoiseMaterial} from 'three-gpu-pathtracer';
import {FullScreenQuad} from 'three/addons/postprocessing/Pass.js';
import {solar} from './solar.js';
const $=id=>document.getElementById(id),F=1200/3937,canvas=$('scene');
let data,house,pt,renderer,scene,camera,orbit,sun,skyTex,meshes=[],trees=[],glasses=[],blocks=[],mode='appearance',sky='clear',level=0,view='walk',siteMap=false,ready=false,yaw=0,pitch=-.09,last=0,drag=null,lastMove=0,toastTimer,lastHud=0;
const keys=new Set(),player={x:14.55,y:19.5},ray=new T.Raycaster(),pointer=new T.Vector2(),v=new T.Vector3(),places=[];
let ss,light,mapTransform,canopyScale=1,skyCases=[],skyTicket=0,quality=512;const hdrCache=new Map();
function sunDirection(){if(!ss)return;const rel=Math.atan2(Math.sin(Math.atan2(ss.x,ss.y)-yaw),Math.cos(Math.atan2(ss.x,ss.y)-yaw));const side=Math.abs(rel)>2.35?'behind you':Math.abs(rel)<.78?'ahead':rel>0?'to your right':'to your left';$('sun-direction').textContent=ss.alt<=0?'☾ Below horizon':sky==='overcast'?'☁ Diffuse sky':`☀ Sun ${side} · ${Math.round(ss.alt)}° up`;}
const inside=(p,poly)=>{let hit=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])hit=!hit;}return hit;};
const meters=poly=>poly.map(p=>p.map(n=>n*F));
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2600);}
function fNow(l=level){return data.indoor.floors[l];}
function ground(x,y,l=level){if(l===1)return fNow(1).base;if(inside([x,y],fNow(0).outline))return fNow(0).base;const i=data.outdoor.zones.findIndex(z=>inside([x,y],meters(z.poly)));return i===3?.8:i===4?.4:.016;}
function safe(x,y,l=level){
 const f=fNow(l),p=[x,y];if(l===1&&!inside(p,f.outline))return false;if(l===0&&!inside(p,meters(data.outdoor.parcel)))return false;
 if(l===0){if(inside(p,meters(data.outdoor.zones[0].poly)))return false;if(inside(p,meters(data.outdoor.zones[5].poly))&&(x<3.0||x>4.03))return false;}
 for(const w of f.walls){const a=w.a,b=w.b,dx=b[0]-a[0],dy=b[1]-a[1],L=Math.hypot(dx,dy),u=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/(L*L)));if(Math.hypot(x-a[0]-u*dx,y-a[1]-u*dy)>.27)continue;
  const pass=w.holes.some(h=>{if(h.window)return false;const hx=h.b[0]-h.a[0],hy=h.b[1]-h.a[1],H=Math.hypot(hx,hy),q=((x-h.a[0])*hx+(y-h.a[1])*hy)/(H*H);return (h.sill??0)<.05&&q>.22/H&&q<1-.22/H;});if(!pass)return false;
 }
 const z=ground(x,y,l);for(const b of blocks){if(b.max[2]<z+.1||b.min[2]>z+1.65)continue;if(x>b.min[0]-.18&&x<b.max[0]+.18&&y>b.min[1]-.18&&y<b.max[1]+.18)return false;}
 return true;
}
function nearest(x,y,l=level){if(safe(x,y,l))return [x,y];for(let r=.2;r<=1.6;r+=.2)for(let j=0;j<24;j++){const a=j*Math.PI/12,xx=x+r*Math.cos(a),yy=y+r*Math.sin(a);if(safe(xx,yy,l))return [xx,yy];}return null;}
function pose(){camera.position.set(player.x,ground(player.x,player.y)+1.62,-player.y);camera.lookAt(player.x+Math.sin(yaw)*Math.cos(pitch),camera.position.y+Math.sin(pitch),-player.y-Math.cos(yaw)*Math.cos(pitch));camera.updateMatrixWorld();pt?.updateCamera();lastMove=performance.now();updateLocation();drawMap();sunDirection();}
function setView(value){hideReference();view=value;orbit.enabled=value==='orbit';$('walk').setAttribute('aria-pressed',value==='walk');$('orbit').setAttribute('aria-pressed',value==='orbit');$('pad').hidden=value!=='walk';if(value==='orbit'){orbit.target.set(player.x,ground(player.x,player.y)+1,-player.y);camera.position.set(player.x+21,22,-player.y+20);orbit.update();pt.updateCamera();}else pose();$('view-hint').textContent=value==='walk'?'Drag to look · tap to move · WASD / arrow keys to walk':'Drag to orbit · wheel / pinch to zoom · tap ground to enter';}
function teleport(x,y,l=level,adjust=false){hideReference();const dest=adjust?nearest(x,y,l):safe(x,y,l)?[x,y]:null;if(!dest){toast('Choose clear floor or ground. Pool and planting are off limits.');return false;}level=l;player.x=dest[0];player.y=dest[1];if(view!=='walk')setView('walk');pose();syncFloor();if(innerWidth<761)hidePanel(true);return true;}
function syncFloor(){$('main-floor').setAttribute('aria-pressed',level===0);$('second-floor').setAttribute('aria-pressed',level===1);drawMap();}
function switchFloor(l){siteMap=false;let p=nearest(player.x,player.y,l);if(!p||!inside(p,fNow(l).outline))p=nearest(...fNow(l).rooms.at(-1).label,l);if(p)teleport(...p,l,true);}
function updateLocation(){const r=fNow().rooms.find(r=>inside([player.x,player.y],r.poly));const outdoor=data.outdoor.zones.find(z=>inside([player.x,player.y],meters(z.poly)));$('location').textContent=r?(level?'Second · ':'Main · ')+r.name:(outdoor?.name.replace(' (inferred edges)','')||'Garden path');const idx=places.findIndex(p=>p.level===level&&(r?p.name===r.name:p.name===outdoor?.name.replace(' (inferred edges)','')));if(idx>=0)$('places').value=String(idx);}
async function updateLighting(){if(ready)hideReference();
 const ticket=++skyTicket,kind=sky;ss=solar($('date').value,+$('time').value,data.indoor);const c=skyCases.find(c=>c.date===$('date').value&&c.time===+$('time').value);if(!c)return;
 sun.position.set(10+ss.x*100,ss.z*100,-20-ss.y*100);sun.target.position.set(10,0,-20);sun.target.updateMatrixWorld();sun.intensity=mode==='direct'&&sky==='clear'&&ss.alt>0?3:0;
 $('clock').textContent=ss.clock;$('sun-info').textContent=ss.alt>0?'Sun '+Math.round(ss.alt)+'° above horizon · '+Math.round(ss.az)+'° compass bearing'+(sky==='overcast'?' · diffuse only':'')+($('date').value.includes('-12-')?' · compare leaf-off trees below':''):'Sun below the horizon';
 $('render-state').textContent='Loading atmospheric sky…';
 let tex;if(kind==='clear'){
  if(!hdrCache.has(c.hdr)&&hdrCache.size>=2){const oldest=hdrCache.keys().next().value;hdrCache.get(oldest).then(t=>{if(t!==skyTex)t.dispose();});hdrCache.delete(oldest);}
  if(!hdrCache.has(c.hdr))hdrCache.set(c.hdr,new RGBELoader().loadAsync(c.hdr));tex=await hdrCache.get(c.hdr);tex.mapping=T.EquirectangularReflectionMapping;
 }else{
  tex=new GradientEquirectTexture(256);tex.generationCallback=(polar,uv,coord,color)=>{const up=Math.cos(polar.phi),v=up>0?c.overcast_zenith*(1+2*up)/3:0;return color.setRGB(v,v,v);};tex.update();
 }
 if(ticket!==skyTicket){if(kind==='overcast')tex.dispose();return;}
 const old=skyTex;skyTex=tex;scene.environment=tex;scene.background=tex;scene.environmentIntensity=mode==='direct'?0:1;scene.backgroundIntensity=1;
 pt?.updateEnvironment();pt?.updateLights();if(old?.userData?.temporary)old.dispose();if(kind==='overcast')tex.userData.temporary=true;drawMap();sunDirection();
}
function setMode(value){mode=value;$('appearance').setAttribute('aria-pressed',value==='appearance');$('direct').setAttribute('aria-pressed',value==='direct');pt.bounces=value==='direct'?1:20;for(const m of meshes){if(m.material.name.startsWith('Glazing'))continue;m.material.color.copy(value==='direct'?new T.Color(.65,.65,.65):m.userData.originalColor);m.material.roughness=value==='direct'?1:m.userData.roughness;m.material.map=value==='direct'?null:m.userData.originalMap;}pt.updateMaterials();updateLighting();$('mode-label').textContent=value==='direct'?'DIRECT SUN ONLY · NO SKY OR BOUNCES':'PATH-TRACED DAYLIGHT';if(value==='direct'&&sky==='overcast')toast('Overcast has no direct beam. Use Appearance for diffuse daylight.');}
function addPlaces(){
 const sel=$('places');for(let l=0;l<2;l++){const group=document.createElement('optgroup');group.label=l?'Second floor':'Main floor';fNow(l).rooms.forEach(r=>{const p={name:r.name,x:r.label[0],y:r.label[1],level:l};const i=places.push(p)-1;group.append(new Option(r.name,''+i));});sel.append(group);}
 const g=document.createElement('optgroup');g.label='Garden & grounds';data.outdoor.zones.slice(1).forEach((z,i)=>{const pos=i===4?[3.5,20]:z.label.map(n=>n*F);const p={name:i===4?'Left side path':z.name.replace(' (inferred edges)',''),x:pos[0],y:pos[1],level:0};const idx=places.push(p)-1;g.append(new Option(p.name,''+idx));});sel.append(g);sel.value='1';sel.onchange=()=>{const p=places[+sel.value];siteMap=+sel.value>=14;teleport(p.x,p.y,p.level,true);};
}
function drawMap(){if(!data)return;const svg=$('map'),f=fNow(),poly=siteMap?meters(data.outdoor.parcel):f.outline,xs=poly.map(p=>p[0]),ys=poly.map(p=>p[1]);const minX=Math.min(...xs)-.7,maxX=Math.max(...xs)+.7,minY=Math.min(...ys)-.7,maxY=Math.max(...ys)+.7;const sc=Math.min(275/(maxX-minX),225/(maxY-minY)),cx=(minX+maxX)/2,cy=(minY+maxY)/2;const X=x=>150+(x-cx)*sc,Y=y=>140-(y-cy)*sc;mapTransform={sc,cx,cy};let html='';const shape=(p,fill,stroke='#526b75')=>`<polygon points="${p.map(q=>X(q[0])+','+Y(q[1])).join(' ')}" fill="${fill}" stroke="${stroke}" stroke-width="1"/>`;
 if(siteMap){html+=shape(poly,'#253f38');for(let i=1;i<data.outdoor.zones.length;i++)html+=shape(meters(data.outdoor.zones[i].poly),i===2||i===7?'#304d3d':'#34454d');html+=shape(meters(data.outdoor.zones[0].poly),'#1f6476');html+=shape(f.outline,'#1a282f');for(const idx of [1,2,7,8]){const z=data.outdoor.zones[idx],p=z.label.map(n=>n*F);html+=`<text x="${X(p[0])}" y="${Y(p[1])}" text-anchor="middle">${z.short}</text>`;}}
 else{html+=shape(f.outline,'#25343d');for(const r of f.rooms){html+=shape(r.poly,inside([player.x,player.y],r.poly)?'#415b61':'#25343d');const words=r.name.replace('Kitchen / breakfast','Kitchen').replace('Stairs / landing','Landing').replace('Stairs / hall','Hall').split(' ');html+=`<text text-anchor="middle" x="${X(r.label[0])}" y="${Y(r.label[1])}">${words.map((w,i)=>`<tspan x="${X(r.label[0])}" dy="${i?12:0}">${w}</tspan>`).join('')}</text>`;}for(const w of f.walls){html+=`<path d="M${X(w.a[0])} ${Y(w.a[1])}L${X(w.b[0])} ${Y(w.b[1])}" stroke="#97aeb9" stroke-width="2"/>`;for(const h of w.holes)html+=`<path d="M${X(h.a[0])} ${Y(h.a[1])}L${X(h.b[0])} ${Y(h.b[1])}" stroke="${h.window?'#53b9d4':'#25343d'}" stroke-width="3"/>`;}}
 const px=X(player.x),py=Y(player.y),nx=data.indoor.ux[1],ny=data.indoor.uy[1];html+=`<path d="M270 30l${nx*15} ${-ny*15}" stroke="#b3c6cf" stroke-width="2"/><text x="${270+nx*21}" y="${30-ny*21}" text-anchor="middle">N</text><path d="M${px} ${py}l${Math.sin(yaw)*19} ${-Math.cos(yaw)*19}" stroke="#ffce7a" stroke-width="3"/><circle cx="${px}" cy="${py}" r="5" fill="#ffce7a" stroke="#17262e" stroke-width="2"/><text x="150" y="263" text-anchor="middle">${siteMap?'Cleveland Avenue · front':'Front of house ↓'}</text>`;svg.innerHTML=html;$('map-title').textContent=siteMap?'Property':level?'Second floor':'Main floor';$('map-scope').textContent=siteMap?'Floor plan ↙':'Site map ↗';
}
function mapTap(e){const r=$('map').getBoundingClientRect(),sx=(e.clientX-r.left)*300/r.width,sy=(e.clientY-r.top)*270/r.height,{sc,cx,cy}=mapTransform,x=(sx-150)/sc+cx,y=(140-sy)/sc+cy;const l=siteMap?0:level;const room=fNow(l).rooms.find(r=>inside([x,y],r.poly));teleport(x,y,l,!!room);}
function viewTap(e){const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(meshes,false);const hit=hits.find(h=>!h.object.material.name.startsWith('Glazing')&&!h.object.userData.tree);if(!hit||!hit.object.userData.walkable){toast('Tap a visible floor or clear ground.');return;}const x=hit.point.x,y=-hit.point.z,z=hit.point.y,l=z>3?1:0;if(teleport(x,y,l)){$('destination').style.left=(e.clientX-rect.left)+'px';$('destination').style.top=(e.clientY-rect.top)+'px';$('destination').hidden=false;setTimeout(()=>$('destination').hidden=true,650);}}
function hidePanel(hidden){document.body.classList.toggle('controls-hidden',hidden);$('panel-toggle').setAttribute('aria-expanded',!hidden);setTimeout(resize,0);}
function resize(){if(!renderer)return;const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();pt?.updateCamera();}
function pruneTree(t){
 if(!t.visible)return;t.updateWorldMatrix(true,false);const g=t.geometry,pos=g.attributes.position,idx=t.userData.baseIndex,valid=new Uint8Array(pos.count),p=new T.Vector3();
 for(let i=0;i<pos.count;i++){p.fromBufferAttribute(pos,i).applyMatrix4(t.matrixWorld);const x=p.x,y=-p.z,z=p.y;const blocked=z<8.5&&x>3.9&&x<17.6&&y>13.2&&y<22.55||z<7.4&&data.indoor.floors.some(f=>[[0,0],[.2,0],[-.2,0],[0,.2],[0,-.2]].some(([dx,dy])=>inside([x+dx,y+dy],f.outline)));valid[i]=blocked?0:1;}
 const result=[];for(let i=0;i<idx.length;i+=3)if(valid[idx[i]]&&valid[idx[i+1]]&&valid[idx[i+2]])result.push(idx[i],idx[i+1],idx[i+2]);g.setIndex(result);
}
function setupInput(){
 $('panel-toggle').onclick=()=>hidePanel(!document.body.classList.contains('controls-hidden'));$('map-scope').onclick=()=>{siteMap=!siteMap;drawMap();};$('map').addEventListener('pointerup',mapTap);
 $('main-floor').onclick=()=>switchFloor(0);$('second-floor').onclick=()=>switchFloor(1);$('walk').onclick=()=>setView('walk');$('orbit').onclick=()=>setView('orbit');
 $('date').onchange=()=>{if($('date').value)updateLighting();};$('time').oninput=()=>{$('clock').textContent=solar($('date').value,+$('time').value,data.indoor).clock;};$('time').onchange=updateLighting;
 for(const b of document.querySelectorAll('[data-date]'))b.onclick=()=>{$('date').value=$('date').value.slice(0,4)+'-'+b.dataset.date;updateLighting();};
 for(const s of ['clear','overcast'])$(s).onclick=()=>{sky=s;for(const n of ['clear','overcast'])$(n).setAttribute('aria-pressed',s===n);updateLighting();};
 $('appearance').onclick=()=>setMode('appearance');$('direct').onclick=()=>setMode('direct');
 $('quality').onchange=()=>{hideReference();quality=+$('quality').value;pt.renderScale=quality===2048?1:innerWidth<761?.8:.45;pt.reset();};
 $('exposure').onchange=()=>{hideReference();renderer.toneMappingExposure=+$('exposure').value;pt.reset();$('exposure-badge').textContent=`FIXED ${Math.log2(+$('exposure').value)>0?'+':''}${Math.log2(+$('exposure').value)} EV`;};
 $('glazing').onchange=()=>{hideReference();const trans=+$('glazing').value;for(const m of glasses)m.material.color.setScalar(Math.sqrt(trans/(.96*.96)));pt.updateMaterials();pt.reset();};
 $('canopy').onchange=()=>{hideReference();const s=+$('canopy').value;for(const t of trees){t.visible=s!==0;t.scale.copy(t.userData.originalScale).multiplyScalar(s);const c=t.userData.tree_center;t.position.set(c[0]+(t.userData.originalPosition.x-c[0])*s,c[2]+(t.userData.originalPosition.y-c[2])*s,-c[1]+(t.userData.originalPosition.z+c[1])*s);}canopyScale=s;scene.updateMatrixWorld(true);for(const t of trees)pruneTree(t);pt.setScene(scene,camera);toast('Tree crowns updated. Daylight is recalculating.');};
 canvas.addEventListener('pointerdown',e=>{if(!ready)return;hideReference();drag={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false,id:e.pointerId};canvas.setPointerCapture(e.pointerId);canvas.focus();});
 canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.lastX,dy=e.clientY-drag.lastY;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>7)drag.moved=true;drag.lastX=e.clientX;drag.lastY=e.clientY;if(view==='walk'&&drag.moved){yaw-=dx*.004;pitch=Math.max(-1.4,Math.min(1.4,pitch-dy*.004));pose();}});
 canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved)viewTap(e);drag=null;});canvas.addEventListener('pointercancel',()=>{drag=null;keys.clear();});
 canvas.addEventListener('wheel',e=>{if(view==='walk'){camera.fov=Math.max(35,Math.min(85,camera.fov+e.deltaY*.035));camera.updateProjectionMatrix();pt.updateCamera();}},{passive:true});
 const keymap={KeyW:'forward',ArrowUp:'forward',KeyS:'back',ArrowDown:'back',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};
 window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(keymap[e.code]){e.preventDefault();keys.add(keymap[e.code]);}});window.addEventListener('keyup',e=>keys.delete(keymap[e.code]));window.addEventListener('blur',()=>{keys.clear();drag=null;});
 for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.move);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.move);b.onclick=()=>walkStep(b.dataset.move);}
 $('capture').onclick=()=>{if(pt.samples<128){toast('Let this view reach 128 samples before saving a comparison.');return;}$('compare-img').src=canvas.toDataURL('image/png');$('compare-caption').textContent=`${$('location').textContent} · ${$('date').value} ${ss.clock} · ${sky} · glass ${Math.round(+$('glazing').value*100)}% · trees ${canopyScale?Math.round(canopyScale*100)+'%':'leaf off'} · ${$('exposure-badge').textContent} · ${Math.floor(pt.samples)} samples`;$('comparison').hidden=false;};$('close-compare').onclick=()=>$('comparison').hidden=true;
 $('reference').onclick=()=>$('refs').showModal();$('close-refs').onclick=()=>$('refs').close();
 const refs=[['study-clear','Study · clear',0,14.55,19.5,0,-.09],['study-overcast','Study · overcast',0,14.55,19.5,0,-.09],['sunroom-clear','Sunroom · clear',1,5.7,23.3,0,-.09],['yard-clear','Garden · clear',0,10.8,34,Math.PI,-.06],['pool-clear','Pool · clear',0,10.6,35.9,-2.1,-.35],['bath-clear','Hall bath · clear',1,14.2,20.8,Math.PI/2,-.09]];
 $('ref-grid').innerHTML=refs.map((r,i)=>`<article><img src="/references/${r[0]}.png" alt="Cycles reference: ${r[1]}" loading="lazy"><p>${r[1]} · September 22, 1 PM EDT · +3 EV</p><button data-ref="${i}">Match this view</button></article>`).join('');
 for(const b of document.querySelectorAll('[data-ref]'))b.onclick=()=>{const r=refs[+b.dataset.ref];siteMap=['yard-clear','pool-clear'].includes(r[0]);$('date').value='2026-09-22';$('time').value='780';$(r[0].includes('overcast')?'overcast':'clear').click();$('exposure').value='8';$('exposure').onchange();$('canopy').value='1';$('canopy').onchange();$('glazing').value='.82';$('glazing').selectedIndex=0;$('glazing').onchange();setMode('appearance');yaw=r[5];pitch=r[6];camera.fov=60;camera.updateProjectionMatrix();teleport(r[3],r[4],r[2],true);$('refs').close();};
 new ResizeObserver(resize).observe($('workspace'));
}
function walkStep(direction){hideReference();const a=yaw+({forward:0,back:Math.PI,left:-Math.PI/2,right:Math.PI/2}[direction]||0),x=player.x+Math.sin(a)*.14,y=player.y+Math.cos(a)*.14;if(safe(x,y)){player.x=x;player.y=y;pose();}}
function hideReference(){const el=$('reference-preview');if(el)el.hidden=true;}
function frame(t){requestAnimationFrame(frame);if(!ready)return;const dt=Math.min(.05,(t-last)/1000||.016);last=t;
 if(view==='walk'&&keys.size){hideReference();let f=(keys.has('forward')?1:0)-(keys.has('back')?1:0),r=(keys.has('right')?1:0)-(keys.has('left')?1:0),len=Math.hypot(f,r)||1;const dx=(Math.sin(yaw)*f+Math.cos(yaw)*r)*dt*2/len,dy=(Math.cos(yaw)*f-Math.sin(yaw)*r)*dt*2/len;if(safe(player.x+dx,player.y))player.x+=dx;if(safe(player.x,player.y+dy))player.y+=dy;pose();}
 if(view==='orbit')orbit.update();
 if(pt.samples<quality)pt.renderSample();if(pt.samples>=128)hideReference();
 if(t-lastHud>500){lastHud=t;const n=Math.floor(pt.samples);$('render-state').textContent=`${n} samples · ${n>=quality?'sample limit reached':n<32?'settling':n<128?'refining':'converging'} · ${mode==='appearance'?'20 bounces':'direct only'}`;}
}
async function init(){try{
 [data,blocks,skyCases]=await Promise.all([fetch('/model.json').then(r=>r.json()),fetch('/collision.json').then(r=>r.json()),fetch('/skies/manifest.json').then(r=>r.json())]);
 renderer=new T.WebGLRenderer({canvas,antialias:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.3));renderer.toneMapping=T.ReinhardToneMapping;renderer.toneMappingExposure=8;
 scene=new T.Scene();camera=new T.PerspectiveCamera(60,1,.04,400);orbit=new OrbitControls(camera,canvas);orbit.enabled=false;orbit.enableDamping=false;orbit.minDistance=1;orbit.maxDistance=90;orbit.maxPolarAngle=Math.PI*.48;orbit.addEventListener('change',()=>{if(view==='orbit'){pt?.updateCamera();const dir=camera.getWorldDirection(new T.Vector3());yaw=Math.atan2(dir.x,-dir.z);drawMap();sunDirection();}});
 const gltf=await new GLTFLoader().loadAsync('/house.glb');house=gltf.scene;scene.add(house);
 const materialCopies=new Map();house.traverse(o=>{if(!o.isMesh)return;meshes.push(o);if(!materialCopies.has(o.material.uuid))materialCopies.set(o.material.uuid,o.material.clone());o.material=materialCopies.get(o.material.uuid);o.material.side=T.DoubleSide;o.userData.originalColor=o.material.color.clone();o.userData.roughness=o.material.roughness;o.userData.originalMap=o.material.map;if(o.material.name.startsWith('Glazing')){glasses.push(o);o.material.opacity=1;o.material.transparent=false;o.material.transmission=1;o.material.ior=1.5;o.material.thickness=.005;o.material.attenuationDistance=Infinity;o.material.color.setScalar(Math.sqrt(.82/(.96*.96)));o.material.roughness=.012;}if(o.material.name==='Pool water'){o.material.thickness=.69;o.material.attenuationDistance=3;o.material.attenuationColor=new T.Color(.75,.94,.96);}
if(o.userData.tree){trees.push(o);o.userData.baseIndex=Array.from(o.geometry.index?.array||Array.from({length:o.geometry.attributes.position.count},(_,i)=>i));o.userData.originalScale=o.scale.clone();o.userData.originalPosition=o.position.clone();}});
 sun=new T.DirectionalLight(new T.Color(1,.91,.76),3);scene.add(sun,sun.target);await updateLighting();
 $('loading-detail').textContent='Preparing rays through windows, walls, trees and sky…';pt=new WebGLPathTracer(renderer);pt.bounces=20;pt.transmissiveBounces=24;pt.filterGlossyFactor=.15;pt.renderScale=innerWidth<761?.8:.45;pt.tiles.set(2,2);pt.renderDelay=50;pt.fadeDuration=150;pt.minSamples=1;pt.dynamicLowRes=true;pt.lowResScale=.2;pt.rasterizeScene=false;const denoise=new DenoiseMaterial({sigma:3,kSigma:1,threshold:.2});const denoiseQuad=new FullScreenQuad(denoise);pt.renderToCanvasCallback=(target,r,quad)=>{if(pt.samples<4){quad.render(r);return;}denoise.map=target.texture;denoise.opacity=1;denoiseQuad.render(r);};
 resize();pose();pt.setScene(scene,camera);addPlaces();setupInput();ready=true;$('loading').hidden=true;$('reference-preview').hidden=false;if(innerWidth<761)hidePanel(true);drawMap();requestAnimationFrame(frame);
 window.study={get state(){return {ready,player:{...player},level,view,mode,sky,solar:ss,samples:pt.samples,exposure:renderer.toneMappingExposure,canopyScale,camera:camera.position.toArray()};},safe,teleport,setMode,setView,updateLighting,pose,pt,scene,camera,renderer,data};
 }catch(e){console.error(e);$('loading-detail').textContent=`Unable to start the 3D renderer: ${e.message}. A browser with WebGL 2 is required.`;}}
init();
