(()=>{
 const $=id=>document.getElementById(id),canvas=$('fl-canvas'),model=$('cleveland-indoor-sun').sunModel;
 let gl,program,buffer,loc={},active=false,dirty=true,frameId=0,timer=null,timeJob=0,mesh,labels=[],selected=-1;
 let angle=-.35,elevation=.85,distance=23,target=[10,20,1],basis;
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
 function init(){try{gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('WebGL unavailable');
  const sources=[['VERTEX_SHADER','attribute vec3 aPosition,aColor;uniform vec3 uEye,uRight,uUp,uForward;uniform float uAspect,uTan;varying vec3 vColor;varying float vZ;void main(){vec3 r=aPosition-uEye;float z=dot(r,uForward);gl_Position=vec4(dot(r,uRight)/(uTan*uAspect),dot(r,uUp)/uTan,1.000667*z-0.100033,z);vColor=aColor;vZ=aPosition.z;}'],['FRAGMENT_SHADER','precision mediump float;varying vec3 vColor;varying float vZ;uniform float uCut;void main(){if(vZ>uCut)discard;gl_FragColor=vec4(vColor,1.);}']];
  program=gl.createProgram();for(const [type,src]of sources){const s=gl.createShader(gl[type]);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(program,s);}gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Shader link failed');gl.useProgram(program);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);
  for(const [name,offset]of [['aPosition',0],['aColor',12]]){const n=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(n);gl.vertexAttribPointer(n,3,gl.FLOAT,false,24,offset);}for(const name of ['uEye','uRight','uUp','uForward','uAspect','uTan','uCut'])loc[name]=gl.getUniformLocation(program,name);gl.enable(gl.DEPTH_TEST);return true;
 }catch(e){$('fl-error').hidden=false;console.error(e);return false;}}
 function reset(){const f=model.state().floor,x=f.outline.map(p=>p[0]),y=f.outline.map(p=>p[1]);target=[(Math.min(...x)+Math.max(...x))/2,(Math.min(...y)+Math.max(...y))/2,f.base+.25];distance=23;angle=-.35;elevation=.85;selected=-1;dirty=true;}
 function sync(){if(!$('fl-date').value)return;const floorChanged=$('ci-floor').value!==$('fl-floor').value;for(const name of ['floor','date','time','doors'])$('ci-'+name).value=$('fl-'+name).value;$('ci-canopy').value=$('fl-trees').checked?'full':'none';if(floorChanged){$('ci-floor').dispatchEvent(new Event('change'));reset();}else model.update();dirty=true;}
 function pause(){active=false;cancelAnimationFrame(frameId);clearTimeout(timeJob);stop();}
 function stop(){clearInterval(timer);timer=null;$('fl-play').textContent='Play day';}
 function rebuild(){mesh=window.ClevelandWalk.floorMesh();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,mesh.vertices,gl.STATIC_DRAW);
  const stats=model.stats();$('fl-rooms').replaceChildren();$('fl-labels').replaceChildren();labels=[];
  stats.forEach((r,i)=>{const b=document.createElement('button');b.className='floor-room';b.setAttribute('aria-pressed',String(i===selected));const name=document.createElement('span'),value=document.createElement('strong');name.textContent=r.name;value.textContent=Math.round(r.pct)+'%';b.append(name,value);b.onclick=()=>{selected=i;target=[...mesh.floor.rooms[i].label,mesh.floor.base+.25];distance=13;dirty=true;};$('fl-rooms').appendChild(b);const l=document.createElement('span');l.className='floor-room-label';l.textContent=r.name;$('fl-labels').appendChild(l);labels.push(l);});
  $('fl-clock').textContent=$('ci-clock').textContent;const s=model.sun(+$('fl-time').value,$('fl-date').value),compass=['N','NE','E','SE','S','SW','W','NW'][Math.round(s.az/45)%8];$('fl-sun').textContent=s.z<=0?'Sun below horizon · no direct sun':`Sun from ${compass} · ${Math.round(s.az)}° bearing · ${Math.round(s.alt)}° above horizon`;
  dirty=false;
 }
 function project(p,w,h){const r=p.map((v,i)=>v-basis.eye[i]),z=dot(r,basis.forward),tan=Math.tan(Math.PI/6);return {x:w/2+dot(r,basis.right)/(z*tan)*h/2,y:h/2-dot(r,basis.up)/(z*tan)*h/2,z};}
 function frame(){if(!active)return;if(dirty)rebuild();const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,canvas.clientWidth),h=Math.max(1,canvas.clientHeight);if(canvas.width!==Math.round(w*d)||canvas.height!==Math.round(h*d)){canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);}gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.91,.945,.96,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);
  const sa=Math.sin(angle),ca=Math.cos(angle),se=Math.sin(elevation),ce=Math.cos(elevation),offset=[sa*ce,-ca*ce,se];basis={eye:target.map((v,i)=>v+offset[i]*distance),right:[ca,sa,0],up:[-sa*se,ca*se,ce],forward:offset.map(v=>-v)};
  for(const [key,value]of [['uEye',basis.eye],['uRight',basis.right],['uUp',basis.up],['uForward',basis.forward]])gl.uniform3f(loc[key],...value);gl.uniform1f(loc.uAspect,w/h);gl.uniform1f(loc.uTan,Math.tan(Math.PI/6));gl.uniform1f(loc.uCut,mesh.floor.base+ +$('fl-height').value);gl.drawArrays(gl.TRIANGLES,0,mesh.vertices.length/6);
  labels.forEach((l,i)=>{const p=project([...mesh.floor.rooms[i].label,mesh.floor.base+.10],w,h);l.hidden=!$('fl-label-toggle').checked||p.z<.1||p.x<0||p.x>w||p.y<45||p.y>h-45;l.style.transform=`translate(${p.x}px,${p.y}px) translate(-50%,-50%)`;});drawSun(w,h);frameId=requestAnimationFrame(frame);
 }
 function drawSun(w,h){const s=model.sun(+$('fl-time').value,$('fl-date').value),overlay=$('fl-direction'),ctx=overlay.getContext('2d');if(!ctx)return;const scale=Math.min(2,devicePixelRatio||1);if(overlay.width!==w*scale||overlay.height!==h*scale){overlay.width=w*scale;overlay.height=h*scale;}ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,w,h);if(s.z<=0)return;
  const end=project(target,w,h),start=project(target.map((v,i)=>v+[s.x,s.y,s.z][i]*6),w,h);if(start.z<=0)return;const dx=end.x-start.x,dy=end.y-start.y,len=Math.hypot(dx,dy);if(len<15)return;ctx.strokeStyle='#ad6500';ctx.fillStyle='#ffcb62';ctx.lineWidth=3;ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(end.x,end.y);ctx.stroke();ctx.setLineDash([]);const a=Math.atan2(dy,dx);ctx.beginPath();ctx.moveTo(end.x,end.y);ctx.lineTo(end.x-13*Math.cos(a-.4),end.y-13*Math.sin(a-.4));ctx.lineTo(end.x-13*Math.cos(a+.4),end.y-13*Math.sin(a+.4));ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(start.x,start.y,12,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font='600 12px system-ui';ctx.textAlign='center';ctx.fillStyle='#704400';ctx.fillText('SUN DIRECTION',start.x,start.y-20);
 }
 const overlay=document.createElement('canvas');overlay.id='fl-direction';overlay.setAttribute('aria-hidden','true');canvas.parentElement.appendChild(overlay);
 const pointers=new Map();let gesture;
 function record(){const p=[...pointers.values()];gesture={angle,elevation,distance,x:p[0]?.x||0,y:p[0]?.y||0,span:p.length>1?Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y):0};}
 canvas.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);record();});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const p=[...pointers.values()];if(p.length>1){const span=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y);distance=clamp(gesture.distance*gesture.span/Math.max(span,1),7,42);}else{angle=gesture.angle-(p[0].x-gesture.x)*.008;elevation=clamp(gesture.elevation+(p[0].y-gesture.y)*.006,.18,1.565);}});for(const name of ['pointerup','pointercancel'])canvas.addEventListener(name,e=>{pointers.delete(e.pointerId);record();});
 canvas.addEventListener('wheel',e=>{e.preventDefault();distance=clamp(distance*Math.exp(e.deltaY*.001),7,42);},{passive:false});canvas.addEventListener('keydown',e=>{const k=e.key;if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(k))return;e.preventDefault();if(k==='ArrowLeft')angle+=.12;if(k==='ArrowRight')angle-=.12;if(k==='ArrowUp')elevation=clamp(elevation+.1,.18,1.565);if(k==='ArrowDown')elevation=clamp(elevation-.1,.18,1.565);if(k==='+'||k==='=')distance=clamp(distance*.9,7,42);if(k==='-')distance=clamp(distance/ .9,7,42);});
 $('fl-reset').onclick=reset;$('fl-top').onclick=()=>{elevation=1.565;angle=0;};$('fl-plus').onclick=()=>distance=clamp(distance*.85,7,42);$('fl-minus').onclick=()=>distance=clamp(distance/ .85,7,42);
 for(const id of ['fl-floor','fl-date','fl-trees','fl-doors'])$(id).onchange=sync;$('fl-time').oninput=()=>{clearTimeout(timeJob);timeJob=setTimeout(sync,60);};$('fl-height').oninput=()=>{const m=+$('fl-height').value;$('fl-height-label').textContent=`${m.toFixed(1)} m / ${(m/ .3048).toFixed(1)} ft`;};
 $('fl-play').onclick=()=>{if(timer){stop();return;}if(+$('fl-time').value>=1260)$('fl-time').value=300;$('fl-play').textContent='Pause';timer=setInterval(()=>{const m=+$('fl-time').value+15;if(m>1260){stop();return;}$('fl-time').value=m;sync();},350);};document.addEventListener('sunmodelchange',()=>dirty=true);
 window.ClevelandFloors={activate(){if(active)return;if(!gl&&!init())return;for(const key of ['floor','date','time','doors'])$('fl-'+key).value=$('ci-'+key).value;$('fl-trees').checked=$('ci-canopy').value!=='none';active=true;reset();sync();frameId=requestAnimationFrame(frame);},pause,diagnostics(){return{vertices:mesh?.vertices.length/6,finite:mesh?.vertices.every(Number.isFinite),floor:mesh?.floor.name,basis,active};}};
})();
